accounts/urls.py
from django.urls import path

from . import views

# ここでapp_nameを指定してしまうと、テンプレート、ビューのすべてのURL逆引きを修正する必要があるため、あえて指定しない
#app_name    = "accounts"
urlpatterns = [ 
    path("signup/", views.signup, name="signup"),

    # 書き方を統一させるため前もってas_view化しておく。(一部オーバーライドしている。)
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("password_change/", views.password_change, name="password_change"),
    path("password_change/done/", views.password_change_done, name="password_change_done"),
    path("password_reset/", views.password_reset, name="password_reset"),
    path("password_reset/done/", views.password_reset_done, name="password_reset_done"),
    path("reset/<uidb64>/<token>/", views.password_reset_confirm, name="password_reset_confirm"),
    path("reset/done/", views.password_reset_complete, name="password_reset_complete"),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("nagoyameshi.urls")),

    # URL と ログイン処理を用意する。
    path("accounts/", include("accounts.urls"))
]


"""
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""

nagoyameshi/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name    = "nagoyameshi"
urlpatterns = [
    path('', views.index, name="index"),
    path('restaurant/<int:pk>/', views.restaurant, name="restaurant"),
    path('review/<int:pk>/', views.review, name="review"),
    path('review_edit/<int:pk>/', views.review_edit, name="review_edit"),
    path('review_delete/<int:pk>/', views.review_delete, name="review_delete"),

    path('Fav/<int:pk>/', views.fav, name="fav"),
    path('mypage/', views.mypage, name="mypage"),
    path('reservation/<int:pk>/', views.reservation, name="reservation"),
    path('reservation_cancel/<int:pk>/', views.reservation_cancel, name="reservation_cancel"),
    
    path("checkout/", views.checkout, name="checkout"),
    path("success/", views.success, name="success"),
    path("portal/", views.portal, name="portal"),
    path('premium/', views.premium, name="premium"),
]

#画像のURL設定
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nagoyameshi/models.py
from django.db import models
#最大値と最小値の制限を課せる
from django.core.validators import MinValueValidator,MaxValueValidator
from django.contrib.auth import get_user_model

#Djangoの中にあるユーザーモデルを用意することができる
User = get_user_model()

#Create your models here.
#カテゴリモデル
class Category(models.Model):
    name = models.CharField(verbose_name="カテゴリ名",max_length=10)

    def __str__(self):
        return self.name

    # 文字列型のidを返すメソッド プルダウンで選択した値を固定させるのに必要
    def str_id(self):
        return str(self.id)

#飲食店モデル
class Restaurant(models.Model):
    name = models.CharField(verbose_name="店舗名",max_length=100)
  #カテゴリモデルと紐づくcategory/紐づくCategory-nameが削除されたとき、その飲食店は未分類で残る
    category = models.ForeignKey(Category, verbose_name="カテゴリ", on_delete=models.SET_NULL, null=True, blank=True)
  #画像と説明文
    img = models.ImageField(verbose_name="店舗画像", upload_to="nagoyameshi/restaurant/img")
    description = models.TextField(verbose_name="店舗説明文")
  #登録日と更新日
  #auto_now（_add）で自動的に日時を入力してくれる（修正はできない）
    created_date = models.DateTimeField(verbose_name="作成日",auto_now_add=True)
    update_date = models.DateTimeField(verbose_name="編集日",auto_now=True)
  #予算、受け入れ可能人数（0以上の整数）
    budget = models.PositiveIntegerField(verbose_name="予算")
    capacity = models.PositiveIntegerField(verbose_name="受け入れ可能人数")

  #営業時間
    start = models.TimeField(verbose_name="営業開始")
    end = models.TimeField(verbose_name="営業終了")

# TODO: 追加のバリデーション用
from django.utils import timezone
from django.core.exceptions import ValidationError

#予約モデル
class Reservation(models.Model):
    date = models.DateTimeField(verbose_name="予約日時")
    user = models.ForeignKey(User, verbose_name="予約者", on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, verbose_name="対象飲食店", on_delete=models.CASCADE)
    people = models.PositiveIntegerField(verbose_name="予約人数")

    # Reservationを保存する時、↓の処理が発動される
    # raise ValidationError() をすることで、保存を阻止できる。引数に書いたエラーメッセージを表示できる。
    def clean(self):
        super().clean()

       #peopleがブランクの時
        if self.people == None:
          self.people = 0
          raise ValidationError("予約人数が不明です　")

        # 保存しようとしているデータは self 
        if self.people > self.restaurant.capacity:
            raise ValidationError("受け入れ人数を超過しています　")
               

        now = timezone.now()

        deadline  = now + timezone.timedelta(days=1)
        # one_day_ago = timezone.now() - timezone.timedelta(days=1)
        # print(one_day_ago)
        # if self.date < one_day_ago:
        if self.date < deadline:
            raise ValidationError("この日程では予約できません　")

        # 営業時間のチェック
        if self.date.time() < self.restaurant.start:
            raise ValidationError("営業時間前です　")

        if self.date.time() > self.restaurant.end:
            raise ValidationError("営業時間後です　")

#レビューモデル
class Review(models.Model):
    created_date = models.DateTimeField(verbose_name="作成日時", auto_now_add=True)
    user = models.ForeignKey(User, verbose_name="レビューユーザー", on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, verbose_name="対象飲食店", on_delete=models.CASCADE)
    comment = models.TextField(verbose_name="コメント")
    stars = models.IntegerField(verbose_name="評価", validators=[MinValueValidator(1),MaxValueValidator(5)])

    def star_icon(self):
        dic                 = {}
        dic["true_star"]    = self.stars * " "
        dic["false_star"]   = (5-self.stars)* " "

        return dic


#お気に入り
class Fav(models.Model):
    created_date = models.DateTimeField(verbose_name="登録日",auto_now_add=True)
    user = models.ForeignKey(User, verbose_name="お気に入り登録ユーザー名", on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, verbose_name="対象飲食店", on_delete=models.CASCADE)

    def fav_icon(self):
        dic                 = {}
        dic["on_fav"]    = self.favs * " "
        dic["off_fav"]   = (1-self.favs)* " "

        return dic

#会社情報
class Company(models.Model):
    name = models.CharField(verbose_name="会社名",max_length=20)
    address = models.CharField(verbose_name="所在地",max_length=100)
    phone = models.CharField(verbose_name="電話番号",max_length=15)
    history = models.DateField(verbose_name="設立日")
    terms = models.TextField(verbose_name="規約")

nagoyameshi/forms.py
# 送られてきたデータがルールにあっているかをチェックするために必要
from django import forms
from .models import Restaurant, Review, Fav, Reservation

# Restaurantで検索するためのフォームクラスを作る
class RestaurantCategorySearchForm(forms.ModelForm):

    class Meta:
        model   = Restaurant
        fields  = [ "category" ]

class BudgetSearchForm(forms.ModelForm):

    class Meta:
        model   = Restaurant
        fields  = [ "budget" ]


# Reviewのバリデーション用のフォームを作る
class ReviewForm(forms.ModelForm):

    class Meta:
        model   = Review
        fields  = ["user","restaurant","comment","stars"]

# Review編集用のフォーム
class ReviewEditForm(forms.ModelForm):

    class Meta:
        model   = Review
        fields  = ["comment","stars"]

# Fav のバリデーション用のフォームを作る
class FavForm(forms.ModelForm):
    
    class Meta:
        model   = Fav
        fields  = ["user","restaurant"]

#reservationのバリデーション用フォーム
class ReservationForm(forms.ModelForm):

    class Meta:
        model   = Reservation
        fields  = ["date","user","restaurant","people"]

nagoyameshi/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Restaurant,Category,Review,Fav,Reservation

from .forms import RestaurantCategorySearchForm,ReviewForm,FavForm, ReservationForm, ReviewEditForm



# ページネーション
from django.core.paginator import Paginator 
from django.db.models import Q

# ログイン必須とするために必要
from django.contrib.auth.mixins import LoginRequiredMixin

# DjangoMessageFramework
from django.contrib import messages

#予約時間のバリデーションのため
from django.utils import timezone

#Stripe
import stripe
from django.conf import settings
from django.urls import reverse_lazy

class IndexView(View):

    def get(self, request, *args, **kwargs):
        restaurants = Restaurant.objects.all()
        context={}
        #context["restaurants"]  = Restaurant.objects.all()

        #categoryの全データをcontextに含める
        context["categories"]   = Category.objects.all()
        #バリデーションをするにはnagoyameshiにforms.pyが必要

         # クエリを初期化
        query = Q()

        if "search" in request.GET:
            words =request.GET["search"].replace("　"," ").split(" ")
            for word in words:
                if word=="":
                    continue 
                else:
                    query &=Q(name__contains=word)

        """"                    
            context["restaurants"] = Restaurant.objects.filter(query)
        else:
            print("?search=はありません。検索はしていません。")
            context["restaurants"]  = Restaurant.objects.all()
        """
        form = RestaurantCategorySearchForm(request.GET)

        if form.is_valid():
            #指定されたcategoryを取り出す。
            cleaned = form.clean()

            #category未指定字は条件は追加しない
            if cleaned["category"]:
                query &=Q(category=cleaned["category"])

        #検索されているときも、されていないときも.filter(query)でＯＫ
        #context["restaurants"] = Restaurant.objects.filter(query)
        restaurants     = Restaurant.objects.filter(query)

        # =====ページネーション処理======================

        # 複数のデータを、3個おきにページ区切りにする。
        paginator       = Paginator(restaurants,3)

        # 1ページ分の3件のデータがコンテキストに入る。ページの上限を超えた場合、最後のページが出力される。
        # ページの指定があれば、そのページのデータを表示
        if "page" in request.GET:
            restaurants = paginator.get_page(request.GET["page"])
        # もしページの指定がなければ、1ページめを表示。
        else:
            restaurants = paginator.get_page(1)


        # ページと検索のパラメータを両立させたリンクを作っている
        # request.GET.urlencode() には category=1&search= が入っている。 request.GETは実質辞書型なので {"category":1,"search":""}
        # ↑ に、 page=2を追加したい。
        # request.GET["page"] = 2 で、 {"category":1,"search":"","page":2}としたい。
        # request.GET.urlencode() をすると、 category=1&search=&page=2 になる。

        # ただし、 request.GET["page"] = 2 とすることはできない。
        # request は書き換えできないオブジェクト。だから、まずは、.copy() でコピーのオブジェクトを作る。

        # requestオブジェクトのコピーを作る。
        copied  = request.GET.copy()

        # 飲食店データに前のページはあるか？あれば、リンクを作る。
        if restaurants.has_previous():
            # 1つ前のページ番号をセットする。 copied は {"category":1,"search":"","page":2}
            copied["page"]                      = restaurants.previous_page_number()
            #                                            ↓ category=1&search=&page=2
            restaurants.previous_page_link      = "?" + copied.urlencode()

            # copied は {"category":1,"search":"","page":1}
            copied["page"]                      = 1
            #                                            ↓ category=1&search=&page=1                       
            restaurants.first_page_link         = "?" + copied.urlencode()

        if restaurants.has_next():
            # copied は {"category":1,"search":"","page":4}
            copied["page"]                      = restaurants.next_page_number()
            #                                            ↓ category=1&search=&page=4             
            restaurants.next_page_link          = "?" + copied.urlencode()

            # copied は {"category":1,"search":"","page":10}
            copied["page"]                      = restaurants.paginator.num_pages
            #                                            ↓ category=1&search=&page=10                     
            restaurants.end_page_link           = "?" + copied.urlencode()

        context["restaurants"]  = restaurants

        """
        # name="comment" を取得する場合
        if "comment" in request.GET:
            print( request.GET["comment"] ) 
            # ↑このやり方だと、同じname属性が複数ある場合、最後の一つしか取れない。

            # 複数ある場合、全部をリスト型にして取得するには？
            print( request.GET.getlist("comment") )
        

        if "category_multi" in request.GET:
            print( request.GET.getlist("category_multi") )
            # 検索処理をする。
            
            for category in request.GET.getlist("category_multi"):
                # バリデーション
                query |=Q(category=category)
        
        form = RestaurantCategorySearchForm(request.GET)

        if form.is_valid():
            #指定されたcategoryを取り出す。
            cleaned = form.clean()

            #category未指定字は条件は追加しない
            if cleaned["category"]:
                query &=Q(category=cleaned["category"])
        """
        return render(request,"nagoyameshi/index.html",context)

index   = IndexView.as_view()

# 詳細ページを表示するビューを作る。
class RestaurantView(View):
    def get(self, request, pk, *args, **kwargs):

        # 1件分のRestaurantを出す。pkを使って検索する。
        print(pk)
        context = {}
        context["restaurant"]   = Restaurant.objects.filter(id=pk).first()
        # 飲食店に紐づくレビューを表示させる。Reviewモデルを使う
        # 例: Restaurantのidが1のデータを取り出したい場合、filter()はどうなる？
        # Review.objects.filter(restaurant=1)

        # なのでRestaurantのid(モデルのフィールド)がpk(URLのパスコンバータ)のデータを取り出したい場合
        #Review.objects.filter(restaurant=pk)になる
        context["reviews"]      = Review.objects.filter(restaurant=pk)

        # ユーザーがこの店舗をお気に入り登録しているかをチェックする。

        if request.user.is_authenticated:
            #                                                  ↓未ログイン状態で検索するとエラーになる。
            context["is_faved"]     = Fav.objects.filter(user=request.user,restaurant=context["restaurant"]).exists()
        else:
            context["is_faved"]     = False

        # 有料会員状態をチェックして、その結果をcontextに入れる
        context["is_premium"]       = premium_check(request)

        return render(request, "nagoyameshi/restaurant.html", context)
    
restaurant  = RestaurantView.as_view()

#飲食店のレビューを受け付けるビュー
class ReviewView(View):
    def post(self, request, pk, *args, **kwargs):

        # 有料会員登録をチェックする
        if not premium_check(request):
            messages.info(request, "このサービスをご利用になるには画面右上から有料会員登録を行ってください　")
            return redirect("nagoyameshi:restaurant", pk)

        copied = request.POST.copy()

        # 送られてきたデータではなく、サーバー側でデータをセットして保存できる。
        copied["restaurant"]  = pk
        copied["user"]  = request.user

        #copied["comment"]       = "サーバー側でコメントがセットされました。"
        # 編集されたデータをバリデーションに掛ける。
        form = ReviewForm(copied)
        if form.is_valid():
            form.save()

            # messages を使って、投稿完了をフロントに表示させる。
            messages.success(request, "レビュー投稿が完了しました　")

        else:
            print("保存失敗")
            print(form.errors)
            messages.info(request, "レビュー投稿が失敗しました　")

       #投稿した後は、飲食店詳細ページにリダイレクトする。
        return redirect("nagoyameshi:restaurant", pk)

review = ReviewView.as_view()


# レビュー編集をするビュー
# pkはReviewのid
class ReviewEditView(LoginRequiredMixin,View):
    def get(self, request, pk, *args, **kwargs):
        # 編集したいレビューを表示
        # 自分が投稿したレビューではない場合は店舗検索画面へリダイレクト

        review = Review.objects.filter(id=pk, user=request.user).first()

        if not review:
            print("このレビューは存在しないか、自身で投稿したものではありません。")
            return redirect("nagoyameshi:index")
        context = {}
        context["review"]   = review
        return render(request, "nagoyameshi/review_edit.html", context)
        
    def post(self, request, pk, *args, **kwargs):

        # TODO: ここで編集処理を受け付ける。
        review = Review.objects.filter(id=pk, user=request.user).first()        
        if not review:
            print("このレビューは存在しないか、自分で投稿したものではありません。")
            return redirect("nagoyameshi:index")
        # request.POSTの中に、 stars と comment が入っている。
        # stars と commentをバリデーションする。

        # フォームクラス(データ) この場合、新規作成される。
        # フォームクラス(データ, instance=編集したいオブジェクト)
        form = ReviewEditForm(request.POST, instance=review)

        if form.is_valid():
            form.save()
            messages.success(request, "レビュー編集が完了しました　")
        else:
            print("編集失敗")
            print(form.errors)
            messages.info(request, "レビュー編集が失敗しました　")

        return redirect("nagoyameshi:mypage")

review_edit = ReviewEditView.as_view()

#review削除をするビュー
class ReviewDeleteView(LoginRequiredMixin,View):
    def post(self, request, pk, *args, **kwargs):

        review = Review.objects.filter(id=pk, user=request.user).first()        

        if not review:
            print("このレビューは存在しないか、自分で投稿したものではありません。")
            return redirect("nagoyameshi:index")
        # 削除する。
        review.delete()
        messages.info(request, "投稿レビューを削除しました　")

        return redirect("nagoyameshi:mypage")

review_delete = ReviewDeleteView.as_view()


#飲食店のお気に入りを受けつけるビュー
# お気に入り登録する店舗、すでに登録されていないか、チェックする。
class FavView(View):
    def post(self, request, pk, *args, **kwargs):

       # 有料会員登録をチェックする
        if not premium_check(request):
            messages.info(request, "このサービスをご利用になるには画面右上から有料会員登録を行ってください　")
            return redirect("nagoyameshi:restaurant", pk)

        copied = request.POST.copy()

        # 店舗(restaurant)、ユーザー(user)がFavの中にあるかは .exists() を使う
        fav = Fav.objects.filter(restaurant=pk, user=request.user)
        
        context = {}
        context["is_faved"] = Fav.objects.filter(user=request.user).exists()

        # お気に入り登録している場合は、削除をする。
        if fav:
            fav.delete()
            messages.success(request, "お気に入り登録解除しました　")

templates/nagoyameshi/mypage.html
{% extends "nagoyameshi/base.html" %}

{% block extra_head %}
{% endblock %}

{% block main %}
<!-- 予約の投稿が成功か失敗かのメッセージ表示 -->
<!-- お気に入りの登録やレビュー投稿の成功か失敗かのメッセージ表示 -->
<div class="notify_message_area">
  {% for message in messages %}
  <div class="notify_message notify_message_{{ message.tags }}">
      <div class="notify_message_content">{{ message }}</div>
      <div class="notify_message_delete"><i class="fas fa-times"></i></div>
  </div>
  {% endfor %}
</div>

<h3>マイページ</h3>
{# TODO: これまで登録した自分の、予約、お気に入り、レビューを確認できるようにする。 #}
<h5>登録情報</h5>
<table class="table table-striped table-hover table-bordered">
<thead>
  <tr style="text-align: center;">
      <th>ユーザー名</th>
      <th>登録メールアドレス</th>
      <th>パスワード</th>
      <th>会員タイプ</th>
  </tr>
</thead>
<tr style="text-align: center;">
<td>{{ user.username }}</td>
<td>{{ user.email }}</td>
<td><a href="{% url 'password_reset' %}">パスワードを変更する</a></td>
<td>{% if request.user.paid_member %}
  <a class="button" href="{% url 'nagoyameshi:portal' %}">有料会員登録の設定をする</a>
    {% else %}
    <form action="{% url 'nagoyameshi:checkout' %}" method="post">
      {% csrf_token %}
      <input class="btn btn-warning" type="submit" value="有料会員登録をする">
      </form>
    {% endif %}
</td>
</tr>
</table>
{# reservations #}
<h5>予約履歴一覧</h5>
<table class="table table-striped table-hover table-bordered">
{% if request.user.paid_member %}
  <thead>
  <tr style="text-align: center;">
      <th>店名</th>
      <th>予約日時</th>
      <th>予約人数</th>
      <th>予約の取消</th>
  </tr>
  </thead>
{% for reservation in reservations %}
<tr style="text-align: center;">
    <td>{{ reservation.restaurant.name }}</td>
    <td>{{ reservation.date }}</td>
    <td>{{ reservation.people }}</td>
    <td>
      <form action="{% url 'nagoyameshi:reservation_cancel' reservation.id %}" method="post"  onsubmit="if(confirm('本当に予約を取り消ししますか？')){ return true } else { return false };">
        {% csrf_token %}
        <button class="btn btn-info">予約取消</button>
      </form>
    </td>
</tr>
{% empty %}
<div>まだ予約はありません。</div>
<tr style="text-align: center;">
  <td>-</td>
  <td>-</td>
  <td>-</td>
  <td>-</td>
</tr>
{% endfor %}
{% else %}
<p>このサービスは有料会員の方のみご利用いただけます。</p>
{% endif %}
</table>

{# favs #}
<h5>お気に入り店舗一覧</h5>
<table class="table table-striped table-hover table-bordered">
{% if request.user.paid_member %}
  <thead>
  <tr style="text-align: center;">
      <th>カテゴリ</th>
      <th>店名</th>
      <th>登録日</th>
      <th>店舗ページ</th>
  </tr>
</thead>
{% for fav in favs %}
<tr style="text-align: center;">
    <td>{{ fav.restaurant.category }}</td>
    <td>{{ fav.restaurant.name }}</td>
    <td>{{ fav.created_date }}</td>
    <td><a class="btn btn-info" href="{% url 'nagoyameshi:restaurant' fav.restaurant.id %}">店舗</a></td>
</tr>
{% empty %}
<div>まだお気に入りはありません。</div>
<tr style="text-align: center;">
  <td>-</td>
  <td>-</td>
  <td>-</td>
  <td>-</td>
</tr>
{% endfor %}
{% else %}
<p>このサービスは有料会員の方のみご利用いただけます。</p>
{% endif %}
</table>
<h5>投稿レビュー一覧</h5>
<table class="table table-striped table-hover table-bordered">
{% if request.user.paid_member %}
  <thead>
  <tr style="text-align: center;">
      <th>店名</th>
      <th>評価</th>
      <th>投稿日</th>
      <th>投稿コメント</th>
      <th>店舗ページ</th>
      <th>編集・削除</th>
  </tr>
</thead>
{% for review in reviews %}
<tr style="text-align: center;">
  <td>{{ review.restaurant.name }}</td>
  <td>
    <div class="review_star">
    <span class="review_true_star">{% for s in review.star_icon.true_star %}<i class="fas fa-star"></i>{% endfor %}</span>
    <span class="review_false_star">{% for s in review.star_icon.false_star %}<i class="far fa-star"></i>{% endfor %}</span>
  </div>
  </td>
  <td>{{ review.created_date }}</td>
  <td style="text-align: left;">{{ review.comment }}</td>
  <td><a class="btn btn-info" href="{% url 'nagoyameshi:restaurant' review.restaurant.id %}">店舗</a></td>
  {# 自分が投稿したものに限り、編集のリンクを表示させる。 #}
  <td>
  {% if request.user == review.user %}
  <a class="btn btn-success" href="{% url 'nagoyameshi:review_edit' review.id  %}">編集</a>
  {% endif %}
  </td>
</tr>
{% empty %}
<div>まだレビューはありません。</div>
<tr style="text-align: center;">
  <td>-</td>
  <td>-</td>
  <td>-</td>
  <td>-</td>
  <td>-</td>
</tr>
{% endfor %}
{% else %}
<p>このサービスは有料会員の方のみご利用いただけます。</p>
{% endif %}
</table>



{% endblock %}

templates/nagoyameshi/review_edit.html
{% extends "nagoyameshi/base.html" %}

{% block extra_head %}
{% endblock %}

{% block main %}

<h3>レビュー編集</h3>
<label><i class="fas fa-check"></i>レビューの編集が完了したら送信ボタンを押してください。</label><br>
<label><i class="fas fa-check"></i>レビューを編集削除する場合は削除ボタンを押してください。</label><br>
<h4>店舗名：{{ review.restaurant.name }}</h4>
<table>
  <tr>
      <form action="" method="post">
      {# レビューの星の数選択 #}
      <input id="star_radio_1" type="radio" name="stars" value="1" {% if review.stars == 1 %}checked{% endif %}>
      <input id="star_radio_2" type="radio" name="stars" value="2" {% if review.stars == 2 %}checked{% endif %}>
      <input id="star_radio_3" type="radio" name="stars" value="3" {% if review.stars == 3 %}checked{% endif %}>
      <input id="star_radio_4" type="radio" name="stars" value="4" {% if review.stars == 4 %}checked{% endif %}>
      <input id="star_radio_5" type="radio" name="stars" value="5" {% if review.stars == 5 %}checked{% endif %}>
  
      <div class="star_radio_label_area">
        <div class="star_radio_label_flex">
            <label class="star_radio_label" for="star_radio_5"><div class="true_star" ><i class="fas fa-star"></i></div><div class="false_star"><i class="far fa-star"></i></div></label>
            <label class="star_radio_label" for="star_radio_4"><div class="true_star" ><i class="fas fa-star"></i></div><div class="false_star"><i class="far fa-star"></i></div></label>
            <label class="star_radio_label" for="star_radio_3"><div class="true_star" ><i class="fas fa-star"></i></div><div class="false_star"><i class="far fa-star"></i></div></label>
            <label class="star_radio_label" for="star_radio_2"><div class="true_star" ><i class="fas fa-star"></i></div><div class="false_star"><i class="far fa-star"></i></div></label>
            <label class="star_radio_label" for="star_radio_1"><div class="true_star" ><i class="fas fa-star"></i></div><div class="false_star"><i class="far fa-star"></i></div></label>
        </div>
      </div>
    <div>
      {% csrf_token %}
      {# <p><input style="width: 600px; height: 300px;" type="text" name="comment" value="{{ review.comment }}"></p> #}

      <textarea name="comment" cols="30" rows="10">{{ review.comment }}</textarea>



    </div>
<td>
    <div>
      <input type="submit" value="送信" class="btn btn-info">&nbsp;&nbsp;&nbsp;&nbsp;
    </div>
</form>
</td>
<td>
{# 削除のボタンを作る #}
{# ReviewDeleteView の postメソッドに送信したい。actionにReviewDeleteViewのURLを指定する。action未指定だと、ReviewEditViewのpostメソッドに行き着く。 #}
<form action="{% url 'nagoyameshi:review_delete' review.id %}" method="post" onsubmit="if(confirm('本当に削除しますか？')){ return true } else { return false };">
    {% csrf_token %}
    <input type="submit" value="削除"  class="btn btn-secondary">
</form>
</td>
</tr>
</table>
{% endblock %}